In [2]:
import numpy as np  
import pandas as pd  

import matplotlib.pyplot as plt  
from scipy.stats import norm
%matplotlib inline

data = pd.read_csv('./MSFT_2000.csv', index_col = 'Date')

log_returns = np.log(1 + data.pct_change())
u = log_returns.mean()
var = log_returns.var()
drift = u - (0.5 * var)
stdev = log_returns.std()

******

Use “.values” to transform the *drift* and the *stdev* objects into arrays. 

In [2]:
type(drift)

pandas.core.series.Series

In [3]:
drift.values

array([ -3.42521946e-05])

In [4]:
type(stdev)

pandas.core.series.Series

In [5]:
stdev.values

array([ 0.01939682])

Forecast future stock prices for every trading day a year ahead. So, assign 250 to “t_intervals”. <br />
Let’s examine 10 possible outcomes. Bind “iterations” to the value of 10.

In [6]:
t_intervals = 250
iterations = 10

$$
daily\_returns = e^{r}
$$

$$
r = drift + stdev \cdot z
$$

Use the formula we have provided and calculate daily returns.

$$
daily\_returns = exp({drift} + {stdev} * z), 
$$ 



$$
where\  z = norm.ppf(np.random.rand(t\_intervals, iterations)
$$

In [3]:
norm.ppf(0.95)

1.6448536269514722

In [4]:
x = np.random.rand(10, 2)
x

array([[0.84523149, 0.95150807],
       [0.4893616 , 0.37516023],
       [0.99352572, 0.37797138],
       [0.94964679, 0.84183313],
       [0.48585881, 0.14665638],
       [0.88834722, 0.46546161],
       [0.98974127, 0.11768275],
       [0.82138758, 0.99350225],
       [0.7964031 , 0.38581045],
       [0.73932012, 0.65123666]])

In [5]:
norm.ppf(x)

array([[ 1.01619397,  1.65965513],
       [-0.02666968, -0.31821683],
       [ 2.48518095, -0.31081304],
       [ 1.64143855,  1.00202038],
       [-0.03545414, -1.05088205],
       [ 1.21778535, -0.08668334],
       [ 2.316748  , -1.1866505 ],
       [ 0.920666  ,  2.48389276],
       [ 0.82884205, -0.29025534],
       [ 0.64125079,  0.38866135]])

In [6]:
Z = norm.ppf(np.random.rand(10,2))
Z

array([[ 0.37855753,  0.28370747],
       [-0.17315512,  1.21681995],
       [-0.06197084,  1.05248639],
       [ 0.67975798,  0.85986494],
       [ 1.23486729, -1.55315645],
       [-0.0707761 , -0.70638314],
       [-0.85808764, -3.27964253],
       [ 0.67328578,  0.02909802],
       [ 1.59960991,  0.73166108],
       [-0.06055079, -0.34088724]])

In [7]:
daily_returns = np.exp(drift.values + stdev.values * norm.ppf(np.random.rand(t_intervals, iterations)))
daily_returns

array([[ 1.04349   ,  1.01604234,  1.00293372, ...,  0.98887919,
         1.02431617,  1.00577522],
       [ 1.02119687,  0.98056692,  1.020506  , ...,  1.00942108,
         1.00105479,  1.00671925],
       [ 1.00294186,  0.98998804,  0.99562562, ...,  0.96918634,
         1.02265222,  1.01655192],
       ..., 
       [ 1.00159232,  0.99937562,  1.0216167 , ...,  0.98959137,
         0.99094284,  0.99479379],
       [ 1.0251291 ,  0.97836497,  0.97139958, ...,  1.04597457,
         1.0011809 ,  0.99421068],
       [ 0.99434018,  0.97163049,  0.97613251, ...,  1.00147267,
         0.98800248,  1.02204831]])